services:
  python-app:
    platform: linux/amd64
    image: anuj771/python-app-new.latest:2.0
    build:
      context: .
    ports:
      - "8000:5000"
    volumes:
      - python_data:/var/lib/pythondata


volumes:
  python_data: {}